<html>
<head>
<?php
include "plugin/header.php";
include "plugin/notification.php";
include "config/dbconnect.php";

$sql = mysql_query("SELECT id, mailing_address, country, city FROM auth_userprofile WHERE id = '".$_GET['id']."'");
$data = mysql_fetch_array($sql);
?>
</head>
<body>

<div class="container">
<?php include "plugin/navigation.php"; ?>
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1>Update</h1>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-md-6">
	<form id="form_input" method="POST">

<?php
if(isset($_POST['update']))
{
	mysql_query("UPDATE auth_userprofile SET mailing_address = '".$_POST['mailing_address']."', country = '".$_POST['country']."', city = '".$_POST['city']."' WHERE id = '".$_GET['id']."'");
	writeMsg('update.success');

	$sql = mysql_query("SELECT id, mailing_address, country, city FROM auth_userprofile WHERE id = '".$_GET['id']."'");
	$data = mysql_fetch_array($sql);
}
?>
	<div class="form-group">
  		<label class="control-label" for="mailing_address">Address</label>
  		<input type="text" class="form-control" name="mailing_address" id="mailing_address" value="<?php echo $data['mailing_address']; ?>" required>
	</div>

	<div class="form-group">
  		<label class="control-label" for="country">Country</label>
        <select id="country" name="country" value="<?php echo $data['country']; ?>" required>
        <option value="id">Indonesia</option>
        <option value="af">Afghanistan</option>
        <option value="al">Albania</option>
        <option value="dz">Algeria</option>
        <option value="as">American Samoa</option>
        <option value="ad">Andorra</option>
        <option value="ao">Angola</option>
        <option value="ai">Anguilla</option>
        <option value="aq">Antarctica</option>
        <option value="ag">Antigua and Barbuda</option>
        <option value="ar">Argentina</option>
        <option value="am">Armenia</option>
        <option value="aw">Aruba</option>
        <option value="au">Australia</option>
        <option value="at">Austria</option>
        <option value="az">Azerbaijan</option>
        <option value="bs">Bahamas</option>
        <option value="bh">Bahrain</option>
        <option value="bd">Bangladesh</option>
        <option value="bb">Barbados</option>
        <option value="by">Belarus</option>
        <option value="be">Belgium</option>
        <option value="bz">Belize</option>
        <option value="bj">Benin</option>
        <option value="bm">Bermuda</option>
        <option value="bt">Bhutan</option>
        <option value="bo">Bolivia</option>
        <option value="ba">Bosnia and Herzegovina</option>
        <option value="bw">Botswana</option>
        <option value="bv">Bouvet Island</option>
        <option value="br">Brazil</option>
        <option value="io">British Indian Ocean Territory</option>
        <option value="bn">Brunei Darussalam</option>
        <option value="bg">Bulgaria</option>
        <option value="bf">Burkina Faso</option>
        <option value="bi">Burundi</option>
        <option value="kh">Cambodia</option>
        <option value="cm">Cameroon</option>
        <option value="ca">Canada</option>
        <option value="cv">Cape Verde</option>
        <option value="ky">Cayman Islands</option>
        <option value="cf">Central African Republic</option>
        <option value="td">Chad</option>
        <option value="cl">Chile</option>
        <option value="cn">China</option>
        <option value="cx">Christmas Island</option>
        <option value="cc">Cocos (Keeling) Islands</option>
        <option value="co">Colombia</option>
        <option value="km">Comoros</option>
        <option value="cg">Congo</option>
        <option value="cd">Congo, The Democratic Republic of The</option>
        <option value="ck">Cook Islands</option>
        <option value="cr">Costa Rica</option>
        <option value="ci">Cote D'ivoire</option>
        <option value="hr">Croatia</option>
        <option value="cu">Cuba</option>
        <option value="cy">Cyprus</option>
        <option value="cz">Czech Republic</option>
        <option value="dk">Denmark</option>
        <option value="dj">Djibouti</option>
        <option value="dm">Dominica</option>
        <option value="do">Dominican Republic</option>
        <option value="ec">Ecuador</option>
        <option value="eg">Egypt</option>
        <option value="sv">El Salvador</option>
        <option value="gq">Equatorial Guinea</option>
        <option value="er">Eritrea</option>
        <option value="ee">Estonia</option>
        <option value="et">Ethiopia</option>
        <option value="fk">Falkland Islands (Malvinas)</option>
        <option value="fo">Faroe Islands</option>
        <option value="fj">Fiji</option>
        <option value="fi">Finland</option>
        <option value="fr">France</option>
        <option value="gf">French Guiana</option>
        <option value="pf">French Polynesia</option>
        <option value="tf">French Southern Territories</option>
        <option value="ga">Gabon</option>
        <option value="gm">Gambia</option>
        <option value="ge">Georgia</option>
        <option value="de">Germany</option>
        <option value="gh">Ghana</option>
        <option value="gi">Gibraltar</option>
        <option value="gr">Greece</option>
        <option value="gl">Greenland</option>
        <option value="gd">Grenada</option>
        <option value="gp">Guadeloupe</option>
        <option value="gu">Guam</option>
        <option value="gt">Guatemala</option>
        <option value="gg">Guernsey</option>
        <option value="gn">Guinea</option>
        <option value="gw">Guinea-bissau</option>
        <option value="gy">Guyana</option>
        <option value="ht">Haiti</option>
        <option value="hm">Heard Island and Mcdonald Islands</option>
        <option value="va">Holy See (Vatican City State)</option>
        <option value="hn">Honduras</option>
        <option value="hk">Hong Kong</option>
        <option value="hu">Hungary</option>
        <option value="is">Iceland</option>
        <option value="in">India</option>
        <option value="ir">Iran, Islamic Republic of</option>
        <option value="iq">Iraq</option>
        <option value="ie">Ireland</option>
        <option value="im">Isle of Man</option>
        <option value="il">Israel</option>
        <option value="it">Italy</option>
        <option value="jm">Jamaica</option>
        <option value="jp">Japan</option>
        <option value="je">Jersey</option>
        <option value="jo">Jordan</option>
        <option value="kz">Kazakhstan</option>
        <option value="ke">Kenya</option>
        <option value="ki">Kiribati</option>
        <option value="kp">Korea, Democratic People's Republic of</option>
        <option value="kr">Korea, Republic of</option>
        <option value="kw">Kuwait</option>
        <option value="kg">Kyrgyzstan</option>
        <option value="la">Lao People's Democratic Republic</option>
        <option value="lv">Latvia</option>
        <option value="lb">Lebanon</option>
        <option value="ls">Lesotho</option>
        <option value="lr">Liberia</option>
        <option value="ly">Libyan Arab Jamahiriya</option>
        <option value="li">Liechtenstein</option>
        <option value="lt">Lithuania</option>
        <option value="lu">Luxembourg</option>
        <option value="mo">Macao</option>
        <option value="mk">Macedonia, The Former Yugoslav Republic of</option>
        <option value="mg">Madagascar</option>
        <option value="mw">Malawi</option>
        <option value="my">Malaysia</option>
        <option value="mv">Maldives</option>
        <option value="ml">Mali</option>
        <option value="mt">Malta</option>
        <option value="mh">Marshall Islands</option>
        <option value="mq">Martinique</option>
        <option value="mr">Mauritania</option>
        <option value="mu">Mauritius</option>
        <option value="yt">Mayotte</option>
        <option value="mx">Mexico</option>
        <option value="fm">Micronesia, Federated States of</option>
        <option value="md">Moldova, Republic of</option>
        <option value="mc">Monaco</option>
        <option value="mn">Mongolia</option>
        <option value="me">Montenegro</option>
        <option value="ms">Montserrat</option>
        <option value="ma">Morocco</option>
        <option value="mz">Mozambique</option>
        <option value="mm">Myanmar</option>
        <option value="na">Namibia</option>
        <option value="nr">Nauru</option>
        <option value="np">Nepal</option>
        <option value="nl">Netherlands</option>
        <option value="an">Netherlands Antilles</option>
        <option value="nc">New Caledonia</option>
        <option value="nz">New Zealand</option>
        <option value="ni">Nicaragua</option>
        <option value="ne">Niger</option>
        <option value="ng">Nigeria</option>
        <option value="nu">Niue</option>
        <option value="nf">Norfolk Island</option>
        <option value="mp">Northern Mariana Islands</option>
        <option value="no">Norway</option>
        <option value="om">Oman</option>
        <option value="pk">Pakistan</option>
        <option value="pw">Palau</option>
        <option value="ps">Palestinian Territory, Occupied</option>
        <option value="pa">Panama</option>
        <option value="pg">Papua New Guinea</option>
        <option value="py">Paraguay</option>
        <option value="pe">Peru</option>
        <option value="ph">Philippines</option>
        <option value="pn">Pitcairn</option>
        <option value="pl">Poland</option>
        <option value="pt">Portugal</option>
        <option value="pr">Puerto Rico</option>
        <option value="qa">Qatar</option>
        <option value="re">Reunion</option>
        <option value="ro">Romania</option>
        <option value="ru">Russian Federation</option>
        <option value="rw">Rwanda</option>
        <option value="sh">Saint Helena</option>
        <option value="kn">Saint Kitts and Nevis</option>
        <option value="lc">Saint Lucia</option>
        <option value="pm">Saint Pierre and Miquelon</option>
        <option value="vc">Saint Vincent and The Grenadines</option>
        <option value="ws">Samoa</option>
        <option value="sm">San Marino</option>
        <option value="st">Sao Tome and Principe</option>
        <option value="sa">Saudi Arabia</option>
        <option value="sn">Senegal</option>
        <option value="rs">Serbia</option>
        <option value="sc">Seychelles</option>
        <option value="sl">Sierra Leone</option>
        <option value="sg">Singapore</option>
        <option value="sk">Slovakia</option>
        <option value="si">Slovenia</option>
        <option value="sb">Solomon Islands</option>
        <option value="so">Somalia</option>
        <option value="za">South Africa</option>
        <option value="gs">South Georgia and The South Sandwich Islands</option>
        <option value="es">Spain</option>
        <option value="lk">Sri Lanka</option>
        <option value="sd">Sudan</option>
        <option value="sr">Suriname</option>
        <option value="sj">Svalbard and Jan Mayen</option>
        <option value="sz">Swaziland</option>
        <option value="se">Sweden</option>
        <option value="ch">Switzerland</option>
        <option value="sy">Syrian Arab Republic</option>
        <option value="tw">Taiwan, Province of China</option>
        <option value="tj">Tajikistan</option>
        <option value="tz">Tanzania, United Republic of</option>
        <option value="th">Thailand</option>
        <option value="tl">Timor-leste</option>
        <option value="tg">Togo</option>
        <option value="tk">Tokelau</option>
        <option value="to">Tonga</option>
        <option value="tt">Trinidad and Tobago</option>
        <option value="tn">Tunisia</option>
        <option value="tr">Turkey</option>
        <option value="tm">Turkmenistan</option>
        <option value="tc">Turks and Caicos Islands</option>
        <option value="tv">Tuvalu</option>
        <option value="ug">Uganda</option>
        <option value="ua">Ukraine</option>
        <option value="ae">United Arab Emirates</option>
        <option value="gb">United Kingdom</option>
        <option value="us">United States</option>
        <option value="um">United States Minor Outlying Islands</option>
        <option value="uy">Uruguay</option>
        <option value="uz">Uzbekistan</option>
        <option value="vu">Vanuatu</option>
        <option value="ve">Venezuela</option>
        <option value="vn">Viet Nam</option>
        <option value="vg">Virgin Islands, British</option>
        <option value="vi">Virgin Islands, U.S.</option>
        <option value="wf">Wallis and Futuna</option>
        <option value="eh">Western Sahara</option>
        <option value="ye">Yemen</option>
        <option value="zm">Zambia</option>
        <option value="zw">Zimbabwe</option>
        </select>
	</div>

	<div class="form-group">
  		<label class="control-label" for="city">City</label>
        <select id="city" name="city" value="<?php echo $data['city']; ?>" required>
        <option value="Aceh Barat">Aceh Barat</option>
        <option value="Aceh Barat Daya">Aceh Barat Daya</option>
        <option value="Aceh Besar">Aceh Besar</option>
        <option value="Aceh Jaya">Aceh Jaya</option>
        <option value="Aceh Selatan">Aceh Selatan</option>
        <option value="Aceh Singkil">Aceh Singkil</option>
        <option value="Aceh Tamiang">Aceh Tamiang</option>
        <option value="Aceh Tengah">Aceh Tengah</option>
        <option value="Aceh Tenggara">Aceh Tenggara</option>
        <option value="Aceh Timur">Aceh Timur</option>
        <option value="Aceh Utara">Aceh Utara</option>
        <option value="Agam">Agam</option>
        <option value="Alor">Alor</option>
        <option value="Ambon">Ambon</option>
        <option value="Asahan">Asahan</option>
        <option value="Asmat">Asmat</option>
        <option value="Batam">Batam</option>
        <option value="Badung">Badung</option>
        <option value="Balangan">Balangan</option>
        <option value="Balikpapan">Balikpapan</option>
        <option value="Banda Aceh">Banda Aceh</option>
        <option value="Bandar Lampung">Bandar Lampung</option>
        <option value="Bandung">Bandung</option>
        <option value="Bandung Barat">Bandung Barat</option>
        <option value="Banggai">Banggai</option>
        <option value="Banggai Kepulauan">Banggai Kepulauan</option>
        <option value="Bangka">Bangka</option>
        <option value="Bangka Barat">Bangka Barat</option>
        <option value="Bangka Selatan">Bangka Selatan</option>
        <option value="Bangka Tengah">Bangka Tengah</option>
        <option value="Bangkalan">Bangkalan</option>
        <option value="Bangli">Bangli</option>
        <option value="Banjar">Banjar</option>
        <option value="Banjar Baru">Banjar Baru</option>
        <option value="Banjarmasin">Banjarmasin</option>
        <option value="Banjarnegara">Banjarnegara</option>
        <option value="Bantaeng">Bantaeng</option>
        <option value="Bantul">Bantul</option>
        <option value="Banyu Asin">Banyu Asin</option>
        <option value="Banyumas">Banyumas</option>
        <option value="Banyuwangi">Banyuwangi</option>
        <option value="Barito Kuala">Barito Kuala</option>
        <option value="Barito Selatan">Barito Selatan</option>
        <option value="Barito Timur">Barito Timur</option>
        <option value="Barito Utara">Barito Utara</option>
        <option value="Barru">Barru</option>
        <option value="Baru">Baru</option>
        <option value="Batang">Batang</option>
        <option value="Batang Hari">Batang Hari</option>
        <option value="Batu">Batu</option>
        <option value="Batu Bara">Batu Bara</option>
        <option value="Baubau">Baubau</option>
        <option value="Bekasi">Bekasi</option>
        <option value="Belitung">Belitung</option>
        <option value="Belitung Timur">Belitung Timur</option>
        <option value="Belu">Belu</option>
        <option value="Bener Meriah">Bener Meriah</option>
        <option value="Bengkalis">Bengkalis</option>
        <option value="Bengkayang">Bengkayang</option>
        <option value="Bengkulu">Bengkulu</option>
        <option value="Bengkulu Selatan">Bengkulu Selatan</option>
        <option value="Bengkulu Tengah">Bengkulu Tengah</option>
        <option value="Bengkulu Utara">Bengkulu Utara</option>
        <option value="Berau">Berau</option>
        <option value="Biak Numfor">Biak Numfor</option>
        <option value="Bima">Bima</option>
        <option value="Binjai">Binjai</option>
        <option value="Bintan">Bintan</option>
        <option value="Bireuen">Bireuen</option>
        <option value="Bitung">Bitung</option>
        <option value="Blitar">Blitar</option>
        <option value="Blora">Blora</option>
        <option value="Boalemo">Boalemo</option>
        <option value="Bogor">Bogor</option>
        <option value="Bojonegoro">Bojonegoro</option>
        <option value="Bolaang Mongondow">Bolaang Mongondow</option>
        <option value="Bolaang Mongondow Selatan">Bolaang Mongondow Selatan</option>
        <option value="Bolaang Mongondow Timur">Bolaang Mongondow Timur</option>
        <option value="Bolaang Mongondow Utara">Bolaang Mongondow Utara</option>
        <option value="Bombana">Bombana</option>
        <option value="Bondowoso">Bondowoso</option>
        <option value="Bone">Bone</option>
        <option value="Bone Bolango">Bone Bolango</option>
        <option value="Bontang">Bontang</option>
        <option value="Boven Digoel">Boven Digoel</option>
        <option value="Boyolali">Boyolali</option>
        <option value="Brebes">Brebes</option>
        <option value="Bukittinggi">Bukittinggi</option>
        <option value="Buleleng">Buleleng</option>
        <option value="Bulukumba">Bulukumba</option>
        <option value="Bulungan">Bulungan</option>
        <option value="Bungo">Bungo</option>
        <option value="Buol">Buol</option>
        <option value="Buru">Buru</option>
        <option value="Buru Selatan">Buru Selatan</option>
        <option value="Buton">Buton</option>
        <option value="Buton Utara">Buton Utara</option>
        <option value="Ciamis">Ciamis</option>
        <option value="Cianjur">Cianjur</option>
        <option value="Cilacap">Cilacap</option>
        <option value="Cilegon">Cilegon</option>
        <option value="Cimahi">Cimahi</option>
        <option value="Cirebon">Cirebon</option>
        <option value="Dumai">Dumai</option>
        <option value="Dairi">Dairi</option>
        <option value="Deiyai">Deiyai</option>
        <option value="Deli Serdang">Deli Serdang</option>
        <option value="Demak">Demak</option>
        <option value="Denpasar">Denpasar</option>
        <option value="Depok">Depok</option>
        <option value="Dharmasraya">Dharmasraya</option>
        <option value="Dogiyai">Dogiyai</option>
        <option value="Dompu">Dompu</option>
        <option value="Donggala">Donggala</option>
        <option value="Empat Lawang">Empat Lawang</option>
        <option value="Ende">Ende</option>
        <option value="Enrekang">Enrekang</option>
        <option value="Fakfak">Fakfak</option>
        <option value="Flores Timur">Flores Timur</option>
        <option value="Garut">Garut</option>
        <option value="Gayo Lues">Gayo Lues</option>
        <option value="Gianyar">Gianyar</option>
        <option value="Gorontalo">Gorontalo</option>
        <option value="Gorontalo Utara">Gorontalo Utara</option>
        <option value="Gowa">Gowa</option>
        <option value="Gresik">Gresik</option>
        <option value="Grobogan">Grobogan</option>
        <option value="Gunung Kidul">Gunung Kidul</option>
        <option value="Gunung Mas">Gunung Mas</option>
        <option value="Gunungsitoli">Gunungsitoli</option>
        <option value="Halmahera Barat">Halmahera Barat</option>
        <option value="Halmahera Selatan">Halmahera Selatan</option>
        <option value="Halmahera Tengah">Halmahera Tengah</option>
        <option value="Halmahera Timur">Halmahera Timur</option>
        <option value="Halmahera Utara">Halmahera Utara</option>
        <option value="Hulu Sungai Selatan">Hulu Sungai Selatan</option>
        <option value="Hulu Sungai Tengah">Hulu Sungai Tengah</option>
        <option value="Hulu Sungai Utara">Hulu Sungai Utara</option>
        <option value="Humbang Hasundutan">Humbang Hasundutan</option>
        <option value="Indragiri Hilir">Indragiri Hilir</option>
        <option value="Indragiri Hulu">Indragiri Hulu</option>
        <option value="Indramayu">Indramayu</option>
        <option value="Intan Jaya">Intan Jaya</option>
        <option value="Jakarta">Jakarta</option>
        <option value="Jakarta Barat">Jakarta Barat</option>
        <option value="Jakarta Pusat">Jakarta Pusat</option>
        <option value="Jakarta Selatan">Jakarta Selatan</option>
        <option value="Jakarta Timur">Jakarta Timur</option>
        <option value="Jakarta Utara">Jakarta Utara</option>
        <option value="Jambi">Jambi</option>
        <option value="Jayapura">Jayapura</option>
        <option value="Jayawijaya">Jayawijaya</option>
        <option value="Jember">Jember</option>
        <option value="Jembrana">Jembrana</option>
        <option value="Jeneponto">Jeneponto</option>
        <option value="Jepara">Jepara</option>
        <option value="Jombang">Jombang</option>
        <option value="Kaimana">Kaimana</option>
        <option value="Kampar">Kampar</option>
        <option value="Kapuas">Kapuas</option>
        <option value="Kapuas Hulu">Kapuas Hulu</option>
        <option value="Karang Asem">Karang Asem</option>
        <option value="Karanganyar">Karanganyar</option>
        <option value="Karawang">Karawang</option>
        <option value="Karimun">Karimun</option>
        <option value="Karo">Karo</option>
        <option value="Katingan">Katingan</option>
        <option value="Kaur">Kaur</option>
        <option value="Kayong Utara">Kayong Utara</option>
        <option value="Kebumen">Kebumen</option>
        <option value="Kediri">Kediri</option>
        <option value="Keerom">Keerom</option>
        <option value="Kendal">Kendal</option>
        <option value="Kendari">Kendari</option>
        <option value="Kepahiang">Kepahiang</option>
        <option value="Kepulauan Anambas">Kepulauan Anambas</option>
        <option value="Kepulauan Aru">Kepulauan Aru</option>
        <option value="Kepulauan Mentawai">Kepulauan Mentawai</option>
        <option value="Kepulauan Meranti">Kepulauan Meranti</option>
        <option value="Kepulauan Sangihe">Kepulauan Sangihe</option>
        <option value="Kepulauan Selayar">Kepulauan Selayar</option>
        <option value="Kepulauan Seribu">Kepulauan Seribu</option>
        <option value="Kepulauan Sula">Kepulauan Sula</option>
        <option value="Kepulauan Talaud">Kepulauan Talaud</option>
        <option value="Kepulauan Yapen">Kepulauan Yapen</option>
        <option value="Kerinci">Kerinci</option>
        <option value="Ketapang">Ketapang</option>
        <option value="Klaten">Klaten</option>
        <option value="Klungkung">Klungkung</option>
        <option value="Kolaka">Kolaka</option>
        <option value="Kolaka Utara">Kolaka Utara</option>
        <option value="Konawe">Konawe</option>
        <option value="Konawe Selatan">Konawe Selatan</option>
        <option value="Konawe Utara">Konawe Utara</option>
        <option value="Kotamobagu">Kotamobagu</option>
        <option value="Kotawaringin Barat">Kotawaringin Barat</option>
        <option value="Kotawaringin Timur">Kotawaringin Timur</option>
        <option value="Kuantan Singingi">Kuantan Singingi</option>
        <option value="Kubu Raya">Kubu Raya</option>
        <option value="Kudus">Kudus</option>
        <option value="Kulon Progo">Kulon Progo</option>
        <option value="Kuningan">Kuningan</option>
        <option value="Kupang">Kupang</option>
        <option value="Kutai Barat">Kutai Barat</option>
        <option value="Kutai Kartanegara">Kutai Kartanegara</option>
        <option value="Kutai Timur">Kutai Timur</option>
        <option value="Labuhan Batu">Labuhan Batu</option>
        <option value="Labuhan Batu Selatan">Labuhan Batu Selatan</option>
        <option value="Labuhan Batu Utara">Labuhan Batu Utara</option>
        <option value="Lahat">Lahat</option>
        <option value="Lamandau">Lamandau</option>
        <option value="Lamongan">Lamongan</option>
        <option value="Lampung Barat">Lampung Barat</option>
        <option value="Lampung Selatan">Lampung Selatan</option>
        <option value="Lampung Tengah">Lampung Tengah</option>
        <option value="Lampung Timur">Lampung Timur</option>
        <option value="Lampung Utara">Lampung Utara</option>
        <option value="Landak">Landak</option>
        <option value="Langkat">Langkat</option>
        <option value="Langsa">Langsa</option>
        <option value="Lanny Jaya">Lanny Jaya</option>
        <option value="Lebak">Lebak</option>
        <option value="Lebong">Lebong</option>
        <option value="Lembata">Lembata</option>
        <option value="Lhokseumawe">Lhokseumawe</option>
        <option value="Lima Puluh Kota">Lima Puluh Kota</option>
        <option value="Lingga">Lingga</option>
        <option value="Lombok Barat">Lombok Barat</option>
        <option value="Lombok Tengah">Lombok Tengah</option>
        <option value="Lombok Timur">Lombok Timur</option>
        <option value="Lombok Utara">Lombok Utara</option>
        <option value="Lubuklinggau">Lubuklinggau</option>
        <option value="Lumajang">Lumajang</option>
        <option value="Luwu">Luwu</option>
        <option value="Luwu Timur">Luwu Timur</option>
        <option value="Luwu Utara">Luwu Utara</option>
        <option value="Madiun">Madiun</option>
        <option value="Magelang">Magelang</option>
        <option value="Magetan">Magetan</option>
        <option value="Majalengka">Majalengka</option>
        <option value="Majene">Majene</option>
        <option value="Makassar">Makassar</option>
        <option value="Malang">Malang</option>
        <option value="Malinau">Malinau</option>
        <option value="Maluku Barat Daya">Maluku Barat Daya</option>
        <option value="Maluku Tengah">Maluku Tengah</option>
        <option value="Maluku Tenggara">Maluku Tenggara</option>
        <option value="Maluku Tenggara Barat">Maluku Tenggara Barat</option>
        <option value="Mamasa">Mamasa</option>
        <option value="Mamberamo Raya">Mamberamo Raya</option>
        <option value="Mamberamo Tengah">Mamberamo Tengah</option>
        <option value="Mamuju">Mamuju</option>
        <option value="Mamuju Utara">Mamuju Utara</option>
        <option value="Manado">Manado</option>
        <option value="Mandailing Natal">Mandailing Natal</option>
        <option value="Manggarai">Manggarai</option>
        <option value="Manggarai Barat">Manggarai Barat</option>
        <option value="Manggarai Timur">Manggarai Timur</option>
        <option value="Manokwari">Manokwari</option>
        <option value="Mappi">Mappi</option>
        <option value="Maros">Maros</option>
        <option value="Mataram">Mataram</option>
        <option value="Maybrat">Maybrat</option>
        <option value="Medan">Medan</option>
        <option value="Melawi">Melawi</option>
        <option value="Merangin">Merangin</option>
        <option value="Merauke">Merauke</option>
        <option value="Mesuji">Mesuji</option>
        <option value="Metro">Metro</option>
        <option value="Mimika">Mimika</option>
        <option value="Minahasa">Minahasa</option>
        <option value="Minahasa Selatan">Minahasa Selatan</option>
        <option value="Minahasa Tenggara">Minahasa Tenggara</option>
        <option value="Minahasa Utara">Minahasa Utara</option>
        <option value="Mojokerto">Mojokerto</option>
        <option value="Morowali">Morowali</option>
        <option value="Muara Enim">Muara Enim</option>
        <option value="Muaro Jambi">Muaro Jambi</option>
        <option value="Mukomuko">Mukomuko</option>
        <option value="Muna">Muna</option>
        <option value="Murung Raya">Murung Raya</option>
        <option value="Musi Banyuasin">Musi Banyuasin</option>
        <option value="Musi Rawas">Musi Rawas</option>
        <option value="Nabire">Nabire</option>
        <option value="Nagan Raya">Nagan Raya</option>
        <option value="Nagekeo">Nagekeo</option>
        <option value="Natuna">Natuna</option>
        <option value="Nduga">Nduga</option>
        <option value="Ngada">Ngada</option>
        <option value="Nganjuk">Nganjuk</option>
        <option value="Ngawi">Ngawi</option>
        <option value="Nias">Nias</option>
        <option value="Nias Barat">Nias Barat</option>
        <option value="Nias Selatan">Nias Selatan</option>
        <option value="Nias Utara">Nias Utara</option>
        <option value="Nunukan">Nunukan</option>
        <option value="Ogan Ilir">Ogan Ilir</option>
        <option value="Ogan Komering Ilir">Ogan Komering Ilir</option>
        <option value="Ogan Komering Ulu">Ogan Komering Ulu</option>
        <option value="Ogan Komering Ulu Selatan">Ogan Komering Ulu Selatan</option>
        <option value="Ogan Komering Ulu Timur">Ogan Komering Ulu Timur</option>
        <option value="Pacitan">Pacitan</option>
        <option value="Padang">Padang</option>
        <option value="Padang Lawas">Padang Lawas</option>
        <option value="Padang Lawas Utara">Padang Lawas Utara</option>
        <option value="Padang Panjang">Padang Panjang</option>
        <option value="Padang Pariaman">Padang Pariaman</option>
        <option value="Padangsidimpuan">Padangsidimpuan</option>
        <option value="Pagar Alam">Pagar Alam</option>
        <option value="Pakpak Bharat">Pakpak Bharat</option>
        <option value="Palangka Raya">Palangka Raya</option>
        <option value="Palembang">Palembang</option>
        <option value="Palopo">Palopo</option>
        <option value="Palu">Palu</option>
        <option value="Pamekasan">Pamekasan</option>
        <option value="Pandeglang">Pandeglang</option>
        <option value="Pangandaran">Pangandaran</option>
        <option value="Pangkajene Dan Kepulauan">Pangkajene Dan Kepulauan</option>
        <option value="Pangkal Pinang">Pangkal Pinang</option>
        <option value="Paniai">Paniai</option>
        <option value="Parepare">Parepare</option>
        <option value="Pariaman">Pariaman</option>
        <option value="Parigi Moutong">Parigi Moutong</option>
        <option value="Pasaman">Pasaman</option>
        <option value="Pasaman Barat">Pasaman Barat</option>
        <option value="Paser">Paser</option>
        <option value="Pasuruan">Pasuruan</option>
        <option value="Pati">Pati</option>
        <option value="Payakumbuh">Payakumbuh</option>
        <option value="Pegunungan Bintang">Pegunungan Bintang</option>
        <option value="Pekalongan">Pekalongan</option>
        <option value="Pekanbaru">Pekanbaru</option>
        <option value="Pelalawan">Pelalawan</option>
        <option value="Pemalang">Pemalang</option>
        <option value="Pematang Siantar">Pematang Siantar</option>
        <option value="Penajam Paser Utara">Penajam Paser Utara</option>
        <option value="Pesawaran">Pesawaran</option>
        <option value="Pesisir Barat">Pesisir Barat</option>
        <option value="Pesisir Selatan">Pesisir Selatan</option>
        <option value="Pidie">Pidie</option>
        <option value="Pidie Jaya">Pidie Jaya</option>
        <option value="Pinrang">Pinrang</option>
        <option value="Pohuwato">Pohuwato</option>
        <option value="Polewali Mandar">Polewali Mandar</option>
        <option value="Ponorogo">Ponorogo</option>
        <option value="Pontianak">Pontianak</option>
        <option value="Poso">Poso</option>
        <option value="Prabumulih">Prabumulih</option>
        <option value="Pringsewu">Pringsewu</option>
        <option value="Probolinggo">Probolinggo</option>
        <option value="Pulang Pisau">Pulang Pisau</option>
        <option value="Pulau Morotai">Pulau Morotai</option>
        <option value="Puncak">Puncak</option>
        <option value="Puncak Jaya">Puncak Jaya</option>
        <option value="Purbalingga">Purbalingga</option>
        <option value="Purwakarta">Purwakarta</option>
        <option value="Purworejo">Purworejo</option>
        <option value="Raja Ampat">Raja Ampat</option>
        <option value="Rejang Lebong">Rejang Lebong</option>
        <option value="Rembang">Rembang</option>
        <option value="Rokan Hilir">Rokan Hilir</option>
        <option value="Rokan Hulu">Rokan Hulu</option>
        <option value="Rote Ndao">Rote Ndao</option>
        <option value="S I A K">S I A K</option>
        <option value="Sabang">Sabang</option>
        <option value="Sabu Raijua">Sabu Raijua</option>
        <option value="Salatiga">Salatiga</option>
        <option value="Samarinda">Samarinda</option>
        <option value="Sambas">Sambas</option>
        <option value="Samosir">Samosir</option>
        <option value="Sampang">Sampang</option>
        <option value="Sanggau">Sanggau</option>
        <option value="Sarmi">Sarmi</option>
        <option value="Sarolangun">Sarolangun</option>
        <option value="Sawah Lunto">Sawah Lunto</option>
        <option value="Sekadau">Sekadau</option>
        <option value="Seluma">Seluma</option>
        <option value="Semarang">Semarang</option>
        <option value="Seram Bagian Barat">Seram Bagian Barat</option>
        <option value="Seram Bagian Timur">Seram Bagian Timur</option>
        <option value="Serang">Serang</option>
        <option value="Serdang Bedagai">Serdang Bedagai</option>
        <option value="Seruyan">Seruyan</option>
        <option value="Siau Tagulandang Biaro">Siau Tagulandang Biaro</option>
        <option value="Sibolga">Sibolga</option>
        <option value="Sidenreng Rappang">Sidenreng Rappang</option>
        <option value="Sidoarjo">Sidoarjo</option>
        <option value="Sigi">Sigi</option>
        <option value="Sijunjung">Sijunjung</option>
        <option value="Sikka">Sikka</option>
        <option value="Simalungun">Simalungun</option>
        <option value="Simeulue">Simeulue</option>
        <option value="Singkawang">Singkawang</option>
        <option value="Sinjai">Sinjai</option>
        <option value="Sintang">Sintang</option>
        <option value="Situbondo">Situbondo</option>
        <option value="Sleman">Sleman</option>
        <option value="Solok">Solok</option>
        <option value="Solok Selatan">Solok Selatan</option>
        <option value="Soppeng">Soppeng</option>
        <option value="Sorong">Sorong</option>
        <option value="Sorong Selatan">Sorong Selatan</option>
        <option value="Sragen">Sragen</option>
        <option value="Subang">Subang</option>
        <option value="Subulussalam">Subulussalam</option>
        <option value="Sukabumi">Sukabumi</option>
        <option value="Sukamara">Sukamara</option>
        <option value="Sukoharjo">Sukoharjo</option>
        <option value="Sumba Barat">Sumba Barat</option>
        <option value="Sumba Barat Daya">Sumba Barat Daya</option>
        <option value="Sumba Tengah">Sumba Tengah</option>
        <option value="Sumba Timur">Sumba Timur</option>
        <option value="Sumbawa">Sumbawa</option>
        <option value="Sumbawa Barat">Sumbawa Barat</option>
        <option value="Sumedang">Sumedang</option>
        <option value="Sumenep">Sumenep</option>
        <option value="Sungai Penuh">Sungai Penuh</option>
        <option value="Supiori">Supiori</option>
        <option value="Surabaya">Surabaya</option>
        <option value="Surakarta">Surakarta</option>
        <option value="Tabalong">Tabalong</option>
        <option value="Tabanan">Tabanan</option>
        <option value="Takalar">Takalar</option>
        <option value="Tambrauw">Tambrauw</option>
        <option value="Tana Tidung">Tana Tidung</option>
        <option value="Tana Toraja">Tana Toraja</option>
        <option value="Tanah Bumbu">Tanah Bumbu</option>
        <option value="Tanah Datar">Tanah Datar</option>
        <option value="Tanah Laut">Tanah Laut</option>
        <option value="Tangerang">Tangerang</option>
        <option value="Tangerang Selatan">Tangerang Selatan</option>
        <option value="Tanggamus">Tanggamus</option>
        <option value="Tanjung Balai">Tanjung Balai</option>
        <option value="Tanjung Jabung Barat">Tanjung Jabung Barat</option>
        <option value="Tanjung Jabung Timur">Tanjung Jabung Timur</option>
        <option value="Tanjung Pinang">Tanjung Pinang</option>
        <option value="Tapanuli Selatan">Tapanuli Selatan</option>
        <option value="Tapanuli Tengah">Tapanuli Tengah</option>
        <option value="Tapanuli Utara">Tapanuli Utara</option>
        <option value="Tapin">Tapin</option>
        <option value="Tarakan">Tarakan</option>
        <option value="Tasikmalaya">Tasikmalaya</option>
        <option value="Tebing Tinggi">Tebing Tinggi</option>
        <option value="Tebo">Tebo</option>
        <option value="Tegal">Tegal</option>
        <option value="Teluk Bintuni">Teluk Bintuni</option>
        <option value="Teluk Wondama">Teluk Wondama</option>
        <option value="Temanggung">Temanggung</option>
        <option value="Ternate">Ternate</option>
        <option value="Tidore Kepulauan">Tidore Kepulauan</option>
        <option value="Timor Tengah Selatan">Timor Tengah Selatan</option>
        <option value="Timor Tengah Utara">Timor Tengah Utara</option>
        <option value="Toba Samosir">Toba Samosir</option>
        <option value="Tojo Una-una">Tojo Una-una</option>
        <option value="Tolikara">Tolikara</option>
        <option value="Toli-toli">Toli-toli</option>
        <option value="Tomohon">Tomohon</option>
        <option value="Toraja Utara">Toraja Utara</option>
        <option value="Trenggalek">Trenggalek</option>
        <option value="Tual">Tual</option>
        <option value="Tuban">Tuban</option>
        <option value="Tulang Bawang Barat">Tulang Bawang Barat</option>
        <option value="Tulangbawang">Tulangbawang</option>
        <option value="Tulungagung">Tulungagung</option>
        <option value="Wajo">Wajo</option>
        <option value="Wakatobi">Wakatobi</option>
        <option value="Waropen">Waropen</option>
        <option value="Way Kanan">Way Kanan</option>
        <option value="Wonogiri">Wonogiri</option>
        <option value="Wonosobo">Wonosobo</option>
        <option value="Yahukimo">Yahukimo</option>
        <option value="Yalimo">Yalimo</option>
        <option value="Yogyakarta">Yogyakarta</option>
        </select>
	</div>

	<div class="form-group">
	<input type="submit" value="Update" name="update" class="btn btn-primary">
	<a href="#" class="btn btn-danger">Batal</a>
	</div>

	</form>
	</div>
</div>

</div>
<?php include "plugin/footer.php"; ?>
</body>
</html>
